### ISSUE TITLE
how do I get the descriptors

### ISSUE THREAD

**Issue by othane** [djpnewton/kowhai#25]
I am looking at the tools/test code in kowhai and I can see POPULATE_PROTOCOL_GET_TREE_LIST() which will get the tree_list. But this has only pointers to the descriptors which are useless once your on a remote machine, how do you get the actual descriptor ?

**Comment by djpnewton** [comment]
something like:

#define POPULATE_PROTOCOL_READ_DESCRIPTOR(protocol) \
{ \
     protocol.header.command = KOW_READ_DESCRIPTOR;\
     protocol.header.id = 0; \
}

**Comment by djpnewton** [comment]
sorry, it takes a tree id too.

test.c uses: "POPULATE_PROTOCOL_CMD(prot, KOW_CMD_READ_DESCRIPTOR, SYM_SETTINGS);"
