### ISSUE TITLE
need merge routine

### ISSUE THREAD

**Issue by othane** [djpnewton/kowhai#9]
Need a routine to merge two trees from dst in src. It should merge nodes (copy values from src into dst) that are common in path between dst and src. Unique items in dst should be left alone (ie retain their values). Unique items in src should be ignored. All array items should be merged accross.

Only matching types should be merged across from src to dst. It may be desirable to allow upcasting ie uint16_t to uint32_t ?

Arrays should be merged if they are the same length. It may be desireable to allow smaller arrays to merge into bigger ones if a uint8_t bitmap[2] can merge into a uint8_t bitmap[5] but not visa versa, or it may be desireable to merge as many elements as will fit ??

**Comment by othane** [comment]
I have started work on this here:
https://github.com/othane/kowhai/tree/kowhai_merge

**Comment by djpnewton** [comment]
So a node will be merged only if it has the exact same symbol path I guess?

On Sun, Dec 4, 2011 at 6:58 PM, Oliver Thane <
reply@reply.github.com

**Comment by othane** [comment]
yeh, to start off with I will write it so that a node is merged only if:
- symbol paths match
- types match (todo maybe allow up-casting?)
- array sizes match (todo maybe allow loading smaller arrays into larger ones, or copy as much as possible etc?)

**Comment by djpnewton** [comment]
this is now in the mainline
